spring.application.name=demo
server.port=8080

nombre=Max

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name=Mi app
info.app.version=1.0.0

spring.security.user.name=Max
spring.security.user.password=8989